USE DATABASE ERP_COPILOT;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME STRING,
    CUSTOMER_EMAIL STRING,
    CUSTOMER_CITY STRING,
    CUSTOMER_COUNTRY STRING,
    CREATED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID INTEGER,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    UNIT_PRICE NUMBER(10,2),
    REORDER_LEVEL INTEGER,
    CREATED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID INTEGER,
    CUSTOMER_ID INTEGER,
    ORDER_DATE DATE,
    STATUS STRING,
    TOTAL_AMOUNT NUMBER(12,2)
);

CREATE OR REPLACE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID INTEGER,
    ORDER_ID INTEGER,
    PRODUCT_ID INTEGER,
    QUANTITY INTEGER,
    UNIT_PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE INVOICES (
    INVOICE_ID INTEGER,
    CUSTOMER_ID INTEGER,
    INVOICE_DATE DATE,
    DUE_DATE DATE,
    AMOUNT NUMBER(12,2),
    STATUS STRING
);

CREATE OR REPLACE TABLE INVENTORY (
    INVENTORY_ID INTEGER,
    PRODUCT_ID INTEGER,
    CURRENT_STOCK INTEGER,
    LAST_UPDATED TIMESTAMP
);  