USE DATABASE ERP_COPILOT;
USE SCHEMA STAGING;

CREATE OR REPLACE VIEW STG_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_EMAIL,
    CUSTOMER_CITY,
    CUSTOMER_COUNTRY,
    CREATED_AT
FROM ERP_COPILOT.RAW.CUSTOMERS;





CREATE OR REPLACE VIEW STG_ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    LOWER(STATUS) AS ORDER_STATUS,
    TOTAL_AMOUNT
FROM ERP_COPILOT.RAW.ORDERS;