USE DATABASE ERP_COPILOT;
USE SCHEMA MART;

CREATE OR REPLACE VIEW CUSTOMER_REVENUE AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    COUNT(o.ORDER_ID) AS TOTAL_ORDERS,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(o.TOTAL_AMOUNT) AS AVG_ORDER_VALUE
FROM ERP_COPILOT.STAGING.STG_CUSTOMERS c
JOIN ERP_COPILOT.STAGING.STG_ORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME;




SELECT *
FROM MART.CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;